// @ts-check
/**
 * JSON Schema ファイルから TypeScript 型宣言を生成する。
 *
 * 入力:  packages/contracts-ts/schemas/*.schema.json
 * 出力:  packages/contracts-ts/generated/types.d.ts
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const pkgRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const schemasDir = join(pkgRoot, "schemas");
const outFile = join(pkgRoot, "generated", "types.d.ts");

async function main() {
  const schemaFiles = readdirSync(schemasDir)
    .filter((f) => f.endsWith(".schema.json"))
    .sort();

  if (schemaFiles.length === 0) {
    throw new Error(`no *.schema.json files found in ${schemasDir}`);
  }

  const parts = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-types.mjs — DO NOT EDIT.",
    " * Source: packages/contracts-ts/schemas/*.schema.json",
    " */",
    "",
  ];

  for (const file of schemaFiles) {
    const schemaPath = join(schemasDir, file);
    const schemaText = readFileSync(schemaPath, "utf8");
    const schema = JSON.parse(schemaText);
    const modelName = file.replace(/\.schema\.json$/, "");

    const ts = await compile(schema, modelName, {
      bannerComment: "",
      additionalProperties: false,
      style: { singleQuote: false },
    });

    parts.push(ts);
  }

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, parts.join("\n"));
  console.log(`wrote ${resolve(outFile)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
