// @ts-check
/**
 * JSON Schema ファイルから Zod スキーマを生成する。
 * $ref を $defs からインライン展開してから json-schema-to-zod に渡すことで、
 * z.any() へのフォールバックを防ぐ。
 *
 * 入力:  packages/contracts-ts/schemas/*.schema.json
 * 出力:  packages/contracts-ts/generated/zod.ts
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const pkgRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const schemasDir = join(pkgRoot, "schemas");
const outFile = join(pkgRoot, "generated", "zod.ts");

/**
 * JSON Schema 内の $ref を $defs からインライン展開する。
 * json-schema-to-zod が $ref を z.any() にフォールバックする問題を回避。
 */
function derefSchema(schema) {
	const defs = schema.$defs || {};

	function resolveNode(node) {
		if (node === null || typeof node !== "object") {
			return node;
		}

		if (Array.isArray(node)) {
			return node.map(resolveNode);
		}

		// $ref を解決
		if (node.$ref && typeof node.$ref === "string") {
			const match = node.$ref.match(/^#\/\$defs\/(.+)$/);
			if (match && defs[match[1]]) {
				// $ref 先の定義をインライン展開 (再帰的に解決)
				return resolveNode(structuredClone(defs[match[1]]));
			}
		}

		// オブジェクトの各プロパティを再帰的に解決
		const resolved = {};
		for (const [key, value] of Object.entries(node)) {
			if (key === "$defs") continue; // $defs 自体は出力に含めない
			resolved[key] = resolveNode(value);
		}
		return resolved;
	}

	return resolveNode(schema);
}

function main() {
	const schemaFiles = readdirSync(schemasDir)
		.filter((f) => f.endsWith(".schema.json"))
		.sort();

	if (schemaFiles.length === 0) {
		throw new Error(`no *.schema.json files found in ${schemasDir}`);
	}

	const parts = [
		"/**",
		" * AUTO-GENERATED by scripts/generate-zod.mjs — DO NOT EDIT.",
		" * Source: packages/contracts-ts/schemas/*.schema.json",
		" */",
		'import { z } from "zod";',
		"",
	];

	for (const file of schemaFiles) {
		const schemaPath = join(schemasDir, file);
		const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
		const modelName = file.replace(/\.schema\.json$/, "");
		const exportName = `${modelName}Schema`;

		// $ref をインライン展開してから Zod 生成
		const dereffed = derefSchema(schema);

		const zodCode = jsonSchemaToZod(dereffed, {
			name: exportName,
			module: "none",
		});

		parts.push(`export ${zodCode}`);
		parts.push("");
	}

	mkdirSync(dirname(outFile), { recursive: true });
	writeFileSync(outFile, parts.join("\n"));
	console.log(`wrote ${resolve(outFile)}`);
}

try {
	main();
} catch (err) {
	console.error(err);
	process.exit(1);
}
