// @ts-check
/**
 * JSON Schema ファイルから Zod スキーマを生成する。
 *
 * 入力:  packages/contracts-ts/schemas/*.schema.json
 * 出力:  packages/contracts-ts/generated/zod.ts
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const pkgRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const schemasDir = join(pkgRoot, "schemas");
const outFile = join(pkgRoot, "generated", "zod.ts");

function main() {
  const schemaFiles = readdirSync(schemasDir)
    .filter((f) => f.endsWith(".schema.json"))
    .sort();

  if (schemaFiles.length === 0) {
    throw new Error(`no *.schema.json files found in ${schemasDir}`);
  }

  const parts = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-zod.mjs — DO NOT EDIT.",
    " * Source: packages/contracts-ts/schemas/*.schema.json",
    " */",
    'import { z } from "zod";',
    "",
  ];

  for (const file of schemaFiles) {
    const schemaPath = join(schemasDir, file);
    const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
    const modelName = file.replace(/\.schema\.json$/, "");
    const exportName = `${modelName}Schema`;

    const zodCode = jsonSchemaToZod(schema, {
      name: exportName,
      module: "none",
    });

    // `jsonSchemaToZod` を `module: "none"` で呼ぶと、返ってくる文字列は
    // `const CalorieMacroResultSchema = z.object({ ... })` の形。
    // export するため先頭に `export ` を付与する。
    parts.push(`export ${zodCode}`);
    parts.push("");
  }

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, parts.join("\n"));
  console.log(`wrote ${resolve(outFile)}`);
}

try {
  main();
} catch (err) {
  console.error(err);
  process.exit(1);
}
